[package]
name = "r-ps1"
version = "0.1.0"
edition = "2024"

[dependencies]
md5 = "0.8.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
# eframe = "0.33.2"
env_logger = "0.11.8"
pixels = "0.15"
winit = "0.30"



[profile.release]
#debug = true
#opt-level = 3
#lto = "fat"
#codegen-units = 1
#panic = "abort"